--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dapro718/LevelChangeDimensionPacket
build-by-default: true
branches:
- main
projects:
  LevelChangeDimensionPacket:
    path: ""
...
